config/routes.rb
Rails.application.routes.draw do
  

  # get "password_resets/new"   => "password_resets#new"
  # get "password_resets/edit/:id"  => "password_resets#edit"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "/"                 => "welcome#index", as: "home"
  get "/welcome/new"      => "welcome#new", as: "the_rules"


  get "/owners"				    => "owners#index", as: "owner"
  get "/owners/new"			  => "owners#new", as: "owners_new"
  post "/owners"			    => "owners#create"
  get "/owners/:id"			=> "owners#show", as: "owners_show"
  get "/owners/:id/edit"	=> "owners#edit", as: "owners_edit"
  put "/owners/:id"			=> "owners#update", as: "owners_update"
  patch "/owners/:id"     	=> "owners#update"
  delete "/owners/:id"		=> "owners#destroy"

  get "/sessions"		=> "sessions#new", as: "login"
  post "/sessions"			=> "sessions#create"
  delete "/sessions"  	=> "sessions#destroy", as: "logout" 

  get "/checkin"      => "owners#checkin_with_cam"
  get "/checkout"       => "owners#checkout"


  resources :password_resets, only: [:new, :create, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/owner.rb
class Owner < ApplicationRecord
  attr_accessor :reset_token
  has_secure_password
  validates :username, presence: true, uniqueness: true
  # validates :email, presence: true, uniqueness: true

  has_attached_file :avatar,
   :default_url => "/assets/profile_pic.jpg"
   validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

   def checkedIn?
   	 self.last_checkin && self.last_checkin > Time.now - 2.hours 
   end

   def self.search(search)
  	where("dog_name LIKE ? OR username LIKE ?", "%#{search}%", "%#{search}%") 
   end




      # below relates to "forgot my password" function - still working on this



   # sets the password reset attributes 
   def create_reset_digest
    self.reset_token = Owner.new_token
    update_attribute(:reset_digest, Owner.digest(reset_token))
    update_attribute(:reset_sent_at, Time.zone.now)
   end

   # sends password reset email
   def send_password_reset_email
    OwnerMailer.password_reset(self).deliver_now
   end

   def self.new_token
    SecureRandom.urlsafe_base64
   end
  
  def self.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end


   private
  # Converts email to all lower-case.
  def downcase_email
    self.email = email.downcase
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
end

app/controllers/owners_controller.rb
class OwnersController < ApplicationController
	def index
		@owners = Owner.where(last_checkin: 2.hours.ago..Time.now).order(:last_checkin => :desc)
		@current_owner = Owner.find(session[:owner_id])
		if params[:search]
			@owners = Owner.search(params[:search]).where(last_checkin: 2.hours.ago..Time.now).order(:last_checkin => :desc)
		else
			@owners = Owner.where(last_checkin: 2.hours.ago..Time.now).order(:last_checkin => :desc)
		end
	end

	def new
		@owner = Owner.new
	end

	def create
		@owner = Owner.new(owner_params)
		if @owner.save
		 session[:owner_id] = @owner.id
		 redirect_to owners_path
		end
	end

	def show
		@current_owner = Owner.find(params[:id])

	end

	def checkin_with_cam
		#to do: add the update to checkin here (rails c syntax)
		Owner.find(session[:owner_id]).update(last_checkin: Time.now)
		render :json => {status: 'ok'}
	end

	def checkin
		if session[:owner_id]
			Owner.find(session[:owner_id]).update(last_checkin: Date.new )
		else
			redirect_to root_route, alert: "Incorrect username/password combination"
		end

	end	

	def checkout
		Owner.find(session[:owner_id]).update(last_checkin: nil)
		render :json => {status: 'ok'}
	end	

	def edit 
		@owner = Owner.find(session[:owner_id])
	end

	def update
		@owner = Owner.find(session[:owner_id])
		Owner.find(session[:owner_id]).update(owner_params)
		if @owner.save
			redirect_to owners_show_path, alert: "Your account has been updated"
		else
			redirect_to owners_edit_path, alert: "Uh oh... something went wrong"
		end
	end

	def destroy

	end

	private

	def owner_params
		params.require(:owner).permit(:username, :email, :dog_name, :avatar, :password, :password_confirmation, :last_checkin)
	end
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  before_action :get_owner, only: [:edit, :update]
  before_action :valid_owner, only: [:edit, :update]

  def new
  end

  def create
  	@owner = Owner.find_by(email: params[:password_reset][:email].downcase)
	 if @owner
	   @owner.create_reset_digest
	   @owner.send_password_reset_email
	   flash[:alert] = "Email sent with password reset instructions"
	   redirect_to login_path
	 else
	   flash.now[:danger] = "Email address not found"
	   render 'new'
	 end
  end

  def edit

  end

  def update
    if params[:owner][:password].empty?
      @owner.errors.add(:password, "can't be empty")
      render 'edit'
    elsif @owner.update_attributes(owner_params)
      log_in @owner
      flash[:success] = "Password has been reset."
      redirect_to @owner
    else
      render 'edit'            
    end
  end
  
private

    def owner_params
      params.require(:owner).permit(:password, :password_confirmation)
    end

  def get_owner
  	@owner = Owner.find_by(email: params[:email])
  end



  # def valid_owner
  # 	unless (@owner && @owner.activated? &&)
  # end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new

  end

  def create
  	@owner = Owner.find_by(username: params[:username])
  	if @owner && @owner.password_digest && @owner.try(:authenticate, params[:password])
  		session[:owner_id] = @owner.id
  		redirect_to owners_url
  	else
  		redirect_to login_url, alert: "Invalid username/password combination"
  	end
  end

  def destroy
  	session[:owner_id] = nil
  	redirect_to home_url, alert: "You have successfully logged out."
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  	
  end

  def new
  	
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/owners_helper.rb
module OwnersHelper
end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title> Bark Buddies </title>
    <%= csrf_meta_tags %>

    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">

    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <!-- Bootstap -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body id="body_style">
   <div id="navwrap">
    <% if session[:owner_id] != nil %>
    <nav id="navbar-main">
        <%= form_tag(owners_path, :method => "get", id: "search-form") do %>
        <%= text_field_tag :search, params[:search], placeholder: "Search visitors...", class: "search-input" %>
          <%= submit_tag "Search", :name => nil, class: "search-btn" %>
        <ul class="nav navbar-nav pull-right" id="navlinks">
          <%= link_to "The Rules", the_rules_path, class: "linkers rule_link" %> &nbsp;
          <%= link_to "Current Visitors", owners_path, class: "linkers" %> &nbsp;
          <%= link_to "My Profile", owners_show_path(session[:owner_id]), class: "linkers" %> &nbsp;
          <%= link_to "Settings", owners_edit_path(session[:owner_id]), class: "linkers settings_link" %> &nbsp;
          <%= link_to "Sign Out", login_path, method: :delete, class: "linkers" %>

      <% end %>
        </ul>
    </nav>
    <% end %>
     </div>
    <%= yield %>
  </body>
</html>

app/views/owners/edit.html.erb
  <br>
  <br>
  <br>
  <br>

  <h1 class="always_title"> Bark Buddies </h1>
<br>
<div id="edit_owner_wrapper">
	<br>
	<br>
	<h1 id="edit_title"> Update Your Account </h1>
	<br>
	<br>
	<fieldset id="edit_fieldset">
		<legend id="edit_legend"> Account Details </legend>
		<div id="edit_owner_form">
		<%= form_for @owner, url: owners_update_path(@owner) do |f| %>
			<div class="edit_field">
				<%= f.label "Username:" %>
				<%= f.text_field :username, size: 20, autocomplete: "off" %>		
			</div>


			<div class="edit_field">
				<%= f.label "Email:" %>
				<%= f.text_field :email, autocomplete: "off" %>
			</div>


			<div class="edit_field">
				<%= f.label "Dog" + " " + "Name:" %>
				<%= f.text_field :dog_name, autocomplete: "off" %>
			</div>

			<div class="edit_field">
				<%= f.label "Profile Picture:" + "   " %> 
				<%= f.file_field :avatar, id: "owner_avatar_edit" %>
			</div>


			<div class="edit_field">
				<%= f.label "Password:" %>
				<%= f.password_field :password, autocomplete: "off" %>
			</div>


			<div class="edit_field">
				<%= f.label :password_confirmation, "Confirm:" %>
				<%= f.password_field :password_confirmation, autocomplete: "off" %>
			</div>

			<div class="edit_field">
			<%= f.submit "Save Changes", class: "btn_style_edit" %>
			</div>
		<% end %>	
	</fieldset>
	<br>
	<br>
	</div>
</div>

app/views/owners/index.html.erb
<script>
document.addEventListener("DOMContentLoaded",function(){
	<%= @current_owner && @current_owner.checkedIn? ? "handleCheckout();" : "handleCheckin();" %>
});

function handleCheckin(){
	$("#checkin_with_cam").click(function(){
		$.ajax({
		  url: "/checkin",
		  method: "GET"
		}).done(function() {
		  $("#checkin_with_cam").html( "Check Out" ).off('click');
		  handleCheckout();
		  $("#dog_pound").prepend(`<div class="col-xs-12 col-sm-6 col-md-4 col-lg-3 boots_index temp_load">
				<img src= "<%= @current_owner.avatar.url %>" onerror="this.src='/assets/profile_pic.jpg';" width ="70px"/><br> <%= @current_owner.dog_name%><br>
				checked in <%= time_ago_in_words(@current_owner.last_checkin||Time.now)%> ago </div>`);
		});
	});
}
function handleCheckout(){
	console.log("handleCHeckout")
	$("#checkin_with_cam").click(function(){
		$.ajax({
		  url: "/checkout",
		  method: "GET"
		}).done(function() {
		  $("#checkin_with_cam").html( "Check In" ).off('click');
		  handleCheckin();
		  $(".temp_load").remove();
		});
	});
}
</script>



<div class="owners_index">
	<br>
	<div id="check_border">
			<h5 id="check_in_title"> At the park? Let other visitors know! </h5> <br>
		<button id="checkin_with_cam"> Check <%= @current_owner && @current_owner.checkedIn? ? "Out" : "In" %></button>
	</div>
 <h1 class="always_title"> Bark Buddies </h1>
	<br>
	<br>
	<br>
	<div id="checkin_back">
		<fieldset id="checkin_fieldset">
			<legend id="checkin_legend">Current Dog Park Visitors</legend>
		<div class="container-fluid checked_in_owners">
			<div id="dog_pound" class="row">
			<% @owners.each do |owner| %>
				<div class="col-xs-12 col-sm-6 col-md-4 col-lg-3 boots_index<%= " temp_load" if @current_owner == owner %>">
					<img src= "<%= owner.avatar.url %>" onerror="this.src='/assets/profile_pic.jpg';" height ="85px"/><br>
					<%= link_to owner.dog_name.titleize, owners_show_path(owner), class: "pagelink" %> <br>
					checked in <%= time_ago_in_words(owner.last_checkin||Time.now)%> ago </div>
			<% end if @owners %>
			</div>
		</div>
		</fieldset>
	</div>
<br>
</div>

<br>
<br>
<br>

app/views/owners/new.html.erb
 <br>
 <br>
 <br>
 <h1 class="always_title"> Bark Buddies </h1>
 <br>
<div id="account_wrapper">
<br>
<h1 id="create_acc"> Create An Account </h1>
<div class="new_owner_form">
	<%= form_for @owner, html: {multipart: true} do |f| %>
	<fieldset id="create_fieldset">
		<legend id="acc_legend"> Enter Account Details: </legend>

			<div class="field">
				<%= f.label "Username:" %>
				<%= f.text_field :username, size: 20, autocomplete: "off" %>		
			</div>


			<div class="field">
				<%= f.label "Email:" %>
				<%= f.text_field :email, autocomplete: "off" %>
			</div>


			<div class="field">
				<%= f.label "Dog" + " " + "Name:" %>
				<%= f.text_field :dog_name, autocomplete: "off" %>
			</div>

			<div class="field">
				<%= f.label "Profile Picture:" + "   " %> 
				<%= f.file_field :avatar %>
			</div>


			<div class="field">
				<%= f.label "Password:" %>
				<%= f.password_field :password, autocomplete: "off" %>
			</div>


			<div class="field">
				<%= f.label :password_confirmation, "Confirm:" %>
				<%= f.password_field :password_confirmation, autocomplete: "off" %>
			</div>


			<div class="actions" class="submit_newAcc">
				<div id="sub"><%= f.submit "Create Account", class: "btn_style" %></div>
			</div>

		</fieldset>
	<% end %>
</div>
</div>

app/views/owners/show.html.erb
<br>
<br>
<br>
<div class="acc_info">
<br>
 <h1 class="always_title"> Bark Buddies </h1>
<br>
<br>
<br>
	<fieldset id="owner_show_fieldset">
		<legend id="owner_show_legend"> <%=@current_owner.username.titleize + "'s" + " " + "Account Information" %></legend>
			<div id="avatar_show">
				<%= image_tag @current_owner.avatar.url, class: "avatar_image" %>
			</div>
			<div class="show_text">
				 The Owner: <%= @current_owner.username %>
			</div>
			<div class="show_text">
				 The pup: <%= @current_owner.dog_name %> 
			</div>
			<div class="show_text">
				 Contact information: <%= @current_owner.email %> 
			</div>
	</fieldset>
	<br>
	<br>
	<br>
	

</div>

app/views/password_resets/edit.html.erb
<% provide(:title, 'Reset password') %>
<h1>Reset password</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@owner, url: password_reset_path(params[:owner_id])) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= hidden_field_tag :email, @owner.email %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Update password", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/password_resets/new.html.erb
<% provide(:title, "Forgot password") %>
<h1>Forgot password</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(:password_reset, url: password_resets_path) do |f| %>
      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.submit "Submit", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>


<!-- The below text belong to sessions new but is not functioning correctly  -->
	  	  <div class="login_field">
	  	  	<%= link_to "Forgot password?", new_password_reset_path, class: "forgot_password" %>
	  	  </div>


<!-- Below text belongs to owners/show - added settings link to bypass this -->
      <div id="edit_account_button" >
        <%= button_to "Edit Account Information", owners_edit_path, class: "btn_style", method: :get %>
      </div>

app/views/welcome/index.html.erb
<div id="homepage_wrap">
	<br>
	<br>
	<br>
	<br>
	<h1 id="homepage_title"> Bark Buddies </h1>
	<br>
	<br>
	<div class="container-fluid">
			<div id="textboxes">
				<br>

				<hr class="hr">
				<br>
				<br>
			<div class="row homepage_wrapper">
				<div class="col-xs-12 col-sm-6">
				<h2 class="textTitle"> How this works:  </h2>
			</div>
				<br>
			<div class="col-xs-12 col-sm-6 textExp">
				<h5 class="homeEx"> Getting your pups to the dog park is easy, but coordinating playtime with their canine pals can be a hassle. No more! Bark Buddies is a platform that allows users to check in and out of their local dog park, letting other dog owners know when their pup is ready to play. </h5>
				<h5 class="homeEx"> Now you don't have to worry about making that trek to the park in the rain only to find out no one else is there... </h5>
				<br> 
				<br>
				</div>

					<br>

			</div>
					<hr class="hr">
					<br>
					<br>
					<br>
			<div class="button_control">
				<%= link_to login_url do
				button_tag "Sign In", id: "sign_in_index"
				end %> 
				<%= link_to owners_new_url do
				button_tag "Sign Up", id: "sign_up_index"
				end %>
			</div>
					<br>
					<br>
		</div>
	</div>
</div>

app/views/welcome/new.html.erb
 <br>
 <br>
 <br>
 <br>
 <h1 class="always_title"> Bark Buddies </h1>
	<div id="rule-wrapper" class="container-fluid">
	<br>
	<br>
		<div class="format">
			<h1 id="rules_title"> The Rules </h1>
			<br>
			<br>
			<hr class="hr-rule">
			<div class="format-inset">
			<br>
				We want you and your dog to have a fun and safe time. By entering our public dog parks, you agree to be financially responsible for any injury caused by your dog and abide by posted rules. Please do not enter the run if you are not confident of your dog’s ability to interact safely with other people and dogs. 
			<br>
			<br>
				Washington Square Park has two dog runs - one for small dogs and one for large dogs. While dogs over 25 pounds are not permitted in the small dog run, small dogs are welcome in the large dog run.
			</div>
			<br>
			<br>
			<hr class="hr-rule">
			<div class="format-inset">

			<br>
			<ul id="all-rules">
				<li class="rules_dot"> No dogs without people. No people without dogs. </li>
				<li class="rules_dot"> All dogs over 6 months of age must be neutered or spayed. </li> 
				<li class="rules_dot"> No aggressive dogs. </li>
				<li class="rules_dot"> Accompany and monitor your dog in the run at all times. </li>
				<li class="rules_dot"> Remain alert! Interrupt overly rough play and mounting. </li>
				<li class="rules_dot"> If your dog gets into a fight or injures another dog, exchange contact information with the other owner and remove your dog from the run. </li>
				<li style="font-style: bold;", class="rules_dot"> You are legally and financially responsible for any injury caused by your dog, even if your dog is with a walker at the time of the incident. </li>
				<li class="rules_dot"> Dogs must be licensed and properly vaccinated. </li>
				<li class="rules_dot"> Do not use the run if your dog has a communicable disease. </li>
				<li class="rules_dot"> Your dog must wear a collar or harness while in the run. </li>
				<li class="rules_dot"> Prong, chain and spike collars are prohibited. </li>
				<li class="rules_dot"> Children must be accompanied by an adult and remain seated. </li>
				<li class="rules_dot"> Dispose of all dog waste. </li>
				<li class="rules_dot"> Prevent digging and excessive barking. </li>
				<li class="rules_dot"> No toys except standard size tennis balls. </li>
				<li class="rules_dot"> No food. </li>
				<li class="rules_dot"> Only dogs 25 pounds and under in the small dog area. Large breed puppies under 25 pounds ARE permitted. </li>
			</ul>
			<br>
			<br>
			</div>
			<hr class="hr-rule">
		<br>
		<br>
		<div id="rules-link">
			<h3 class="text"> More Questions? </h3>
			<h4 class="text-x"> Check <a href="https://static1.squarespace.com/static/5313d3e9e4b0d7a86d52896e/t/53291220e4b00d0eac2720b7/1395200544925/dogcourt.PDF"> here.</a></h4>
			</div>
		</div>

		</div>
		<br>
		<br>
	</div>